# automatically generated by the FlatBuffers compiler, do not modify

# namespace: can

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CanFdFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CanFdFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCanFdFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CanFdFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CanFdFrame
    def DeliveryVtimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CanFdFrame
    def CanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CanFdFrame
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CanFdFrame
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CanFdFrame
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CanFdFrame
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CanFdFrame
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def CanFdFrameStart(builder):
    builder.StartObject(4)

def Start(builder):
    CanFdFrameStart(builder)

def CanFdFrameAddDeliveryVtimeNs(builder, deliveryVtimeNs):
    builder.PrependUint64Slot(0, deliveryVtimeNs, 0)

def AddDeliveryVtimeNs(builder, deliveryVtimeNs):
    CanFdFrameAddDeliveryVtimeNs(builder, deliveryVtimeNs)

def CanFdFrameAddCanId(builder, canId):
    builder.PrependUint32Slot(1, canId, 0)

def AddCanId(builder, canId):
    CanFdFrameAddCanId(builder, canId)

def CanFdFrameAddFlags(builder, flags):
    builder.PrependUint32Slot(2, flags, 0)

def AddFlags(builder, flags):
    CanFdFrameAddFlags(builder, flags)

def CanFdFrameAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    CanFdFrameAddData(builder, data)

def CanFdFrameStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return CanFdFrameStartDataVector(builder, numElems)

def CanFdFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return CanFdFrameEnd(builder)
