# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CoordMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CoordMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCoordMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CoordMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CoordMessage
    def SrcNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CoordMessage
    def DstNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CoordMessage
    def DeliveryVtimeNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CoordMessage
    def SequenceNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CoordMessage
    def Protocol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CoordMessage
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CoordMessage
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # CoordMessage
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CoordMessage
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def CoordMessageStart(builder):
    builder.StartObject(6)

def Start(builder):
    CoordMessageStart(builder)

def CoordMessageAddSrcNodeId(builder, srcNodeId):
    builder.PrependUint32Slot(0, srcNodeId, 0)

def AddSrcNodeId(builder, srcNodeId):
    CoordMessageAddSrcNodeId(builder, srcNodeId)

def CoordMessageAddDstNodeId(builder, dstNodeId):
    builder.PrependUint32Slot(1, dstNodeId, 0)

def AddDstNodeId(builder, dstNodeId):
    CoordMessageAddDstNodeId(builder, dstNodeId)

def CoordMessageAddDeliveryVtimeNs(builder, deliveryVtimeNs):
    builder.PrependUint64Slot(2, deliveryVtimeNs, 0)

def AddDeliveryVtimeNs(builder, deliveryVtimeNs):
    CoordMessageAddDeliveryVtimeNs(builder, deliveryVtimeNs)

def CoordMessageAddSequenceNumber(builder, sequenceNumber):
    builder.PrependUint64Slot(3, sequenceNumber, 0)

def AddSequenceNumber(builder, sequenceNumber):
    CoordMessageAddSequenceNumber(builder, sequenceNumber)

def CoordMessageAddProtocol(builder, protocol):
    builder.PrependUint8Slot(4, protocol, 0)

def AddProtocol(builder, protocol):
    CoordMessageAddProtocol(builder, protocol)

def CoordMessageAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    CoordMessageAddPayload(builder, payload)

def CoordMessageStartPayloadVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPayloadVector(builder, numElems):
    return CoordMessageStartPayloadVector(builder, numElems)

def CoordMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return CoordMessageEnd(builder)

try:
    from typing import List
except:
    pass

class CoordMessageT(object):

    # CoordMessageT
    def __init__(
        self,
        srcNodeId = 0,
        dstNodeId = 0,
        deliveryVtimeNs = 0,
        sequenceNumber = 0,
        protocol = 0,
        payload = None,
    ):
        self.srcNodeId = srcNodeId  # type: int
        self.dstNodeId = dstNodeId  # type: int
        self.deliveryVtimeNs = deliveryVtimeNs  # type: int
        self.sequenceNumber = sequenceNumber  # type: int
        self.protocol = protocol  # type: int
        self.payload = payload  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        coordMessage = CoordMessage()
        coordMessage.Init(buf, pos)
        return cls.InitFromObj(coordMessage)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, coordMessage):
        x = CoordMessageT()
        x._UnPack(coordMessage)
        return x

    # CoordMessageT
    def _UnPack(self, coordMessage):
        if coordMessage is None:
            return
        self.srcNodeId = coordMessage.SrcNodeId()
        self.dstNodeId = coordMessage.DstNodeId()
        self.deliveryVtimeNs = coordMessage.DeliveryVtimeNs()
        self.sequenceNumber = coordMessage.SequenceNumber()
        self.protocol = coordMessage.Protocol()
        if not coordMessage.PayloadIsNone():
            if np is None:
                self.payload = []
                for i in range(coordMessage.PayloadLength()):
                    self.payload.append(coordMessage.Payload(i))
            else:
                self.payload = coordMessage.PayloadAsNumpy()

    # CoordMessageT
    def Pack(self, builder):
        if self.payload is not None:
            if np is not None and type(self.payload) is np.ndarray:
                payload = builder.CreateNumpyVector(self.payload)
            else:
                CoordMessageStartPayloadVector(builder, len(self.payload))
                for i in reversed(range(len(self.payload))):
                    builder.PrependUint8(self.payload[i])
                payload = builder.EndVector()
        CoordMessageStart(builder)
        CoordMessageAddSrcNodeId(builder, self.srcNodeId)
        CoordMessageAddDstNodeId(builder, self.dstNodeId)
        CoordMessageAddDeliveryVtimeNs(builder, self.deliveryVtimeNs)
        CoordMessageAddSequenceNumber(builder, self.sequenceNumber)
        CoordMessageAddProtocol(builder, self.protocol)
        if self.payload is not None:
            CoordMessageAddPayload(builder, payload)
        coordMessage = CoordMessageEnd(builder)
        return coordMessage
