# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SyscMsg(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # SyscMsg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SyscMsg
    def Type_(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # SyscMsg
    def IrqNum(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # SyscMsg
    def Data(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateSyscMsg(builder, type_, irqNum, data):
    builder.Prep(8, 16)
    builder.PrependUint64(data)
    builder.PrependUint32(irqNum)
    builder.PrependUint32(type_)
    return builder.Offset()


class SyscMsgT(object):

    # SyscMsgT
    def __init__(
        self,
        type_ = 0,
        irqNum = 0,
        data = 0,
    ):
        self.type_ = type_  # type: int
        self.irqNum = irqNum  # type: int
        self.data = data  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        syscMsg = SyscMsg()
        syscMsg.Init(buf, pos)
        return cls.InitFromObj(syscMsg)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, syscMsg):
        x = SyscMsgT()
        x._UnPack(syscMsg)
        return x

    # SyscMsgT
    def _UnPack(self, syscMsg):
        if syscMsg is None:
            return
        self.type_ = syscMsg.Type_()
        self.irqNum = syscMsg.IrqNum()
        self.data = syscMsg.Data()

    # SyscMsgT
    def Pack(self, builder):
        return CreateSyscMsg(builder, self.type_, self.irqNum, self.data)
