# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VirtmcuHandshake(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # VirtmcuHandshake
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VirtmcuHandshake
    def Magic(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VirtmcuHandshake
    def Version(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateVirtmcuHandshake(builder, magic, version):
    builder.Prep(4, 8)
    builder.PrependUint32(version)
    builder.PrependUint32(magic)
    return builder.Offset()


class VirtmcuHandshakeT(object):

    # VirtmcuHandshakeT
    def __init__(
        self,
        magic = 0,
        version = 0,
    ):
        self.magic = magic  # type: int
        self.version = version  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        virtmcuHandshake = VirtmcuHandshake()
        virtmcuHandshake.Init(buf, pos)
        return cls.InitFromObj(virtmcuHandshake)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, virtmcuHandshake):
        x = VirtmcuHandshakeT()
        x._UnPack(virtmcuHandshake)
        return x

    # VirtmcuHandshakeT
    def _UnPack(self, virtmcuHandshake):
        if virtmcuHandshake is None:
            return
        self.magic = virtmcuHandshake.Magic()
        self.version = virtmcuHandshake.Version()

    # VirtmcuHandshakeT
    def Pack(self, builder):
        return CreateVirtmcuHandshake(builder, self.magic, self.version)
