# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ZenohSPIHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # ZenohSPIHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ZenohSPIHeader
    def DeliveryVtimeNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ZenohSPIHeader
    def SequenceNumber(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ZenohSPIHeader
    def Size(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # ZenohSPIHeader
    def Cs(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # ZenohSPIHeader
    def CsIndex(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(21))
    # ZenohSPIHeader
    def Padding(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(22))

def CreateZenohSpiheader(builder, deliveryVtimeNs, sequenceNumber, size, cs, csIndex, padding):
    builder.Prep(8, 24)
    builder.PrependUint16(padding)
    builder.PrependUint8(csIndex)
    builder.PrependBool(cs)
    builder.PrependUint32(size)
    builder.PrependUint64(sequenceNumber)
    builder.PrependUint64(deliveryVtimeNs)
    return builder.Offset()


class ZenohSPIHeaderT(object):

    # ZenohSPIHeaderT
    def __init__(
        self,
        deliveryVtimeNs = 0,
        sequenceNumber = 0,
        size = 0,
        cs = False,
        csIndex = 0,
        padding = 0,
    ):
        self.deliveryVtimeNs = deliveryVtimeNs  # type: int
        self.sequenceNumber = sequenceNumber  # type: int
        self.size = size  # type: int
        self.cs = cs  # type: bool
        self.csIndex = csIndex  # type: int
        self.padding = padding  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        zenohSpiheader = ZenohSPIHeader()
        zenohSpiheader.Init(buf, pos)
        return cls.InitFromObj(zenohSpiheader)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, zenohSpiheader):
        x = ZenohSPIHeaderT()
        x._UnPack(zenohSpiheader)
        return x

    # ZenohSPIHeaderT
    def _UnPack(self, zenohSpiheader):
        if zenohSpiheader is None:
            return
        self.deliveryVtimeNs = zenohSpiheader.DeliveryVtimeNs()
        self.sequenceNumber = zenohSpiheader.SequenceNumber()
        self.size = zenohSpiheader.Size()
        self.cs = zenohSpiheader.Cs()
        self.csIndex = zenohSpiheader.CsIndex()
        self.padding = zenohSpiheader.Padding()

    # ZenohSPIHeaderT
    def Pack(self, builder):
        return CreateZenohSpiheader(builder, self.deliveryVtimeNs, self.sequenceNumber, self.size, self.cs, self.csIndex, self.padding)
