# automatically generated by the FlatBuffers compiler, do not modify

# namespace: core

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ZenohFrameHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # ZenohFrameHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ZenohFrameHeader
    def DeliveryVtimeNs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ZenohFrameHeader
    def SequenceNumber(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ZenohFrameHeader
    def Size(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateZenohFrameHeader(builder, deliveryVtimeNs, sequenceNumber, size):
    builder.Prep(8, 24)
    builder.Pad(4)
    builder.PrependUint32(size)
    builder.PrependUint64(sequenceNumber)
    builder.PrependUint64(deliveryVtimeNs)
    return builder.Offset()


class ZenohFrameHeaderT(object):

    # ZenohFrameHeaderT
    def __init__(
        self,
        deliveryVtimeNs = 0,
        sequenceNumber = 0,
        size = 0,
    ):
        self.deliveryVtimeNs = deliveryVtimeNs  # type: int
        self.sequenceNumber = sequenceNumber  # type: int
        self.size = size  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        zenohFrameHeader = ZenohFrameHeader()
        zenohFrameHeader.Init(buf, pos)
        return cls.InitFromObj(zenohFrameHeader)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, zenohFrameHeader):
        x = ZenohFrameHeaderT()
        x._UnPack(zenohFrameHeader)
        return x

    # ZenohFrameHeaderT
    def _UnPack(self, zenohFrameHeader):
        if zenohFrameHeader is None:
            return
        self.deliveryVtimeNs = zenohFrameHeader.DeliveryVtimeNs()
        self.sequenceNumber = zenohFrameHeader.SequenceNumber()
        self.size = zenohFrameHeader.Size()

    # ZenohFrameHeaderT
    def Pack(self, builder):
        return CreateZenohFrameHeader(builder, self.deliveryVtimeNs, self.sequenceNumber, self.size)
