#![allow(clippy::all)] // virtmcu-allow: allow reasoning="FlatBuffers generated code"
                       // automatically generated by the FlatBuffers compiler, do not modify
                       // @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod physics {

        /// Sent by the Physics Gateway back to the Time Authority after each step.
        // struct PhysicsDone, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct PhysicsDone(pub [u8; 16]);
        impl Default for PhysicsDone {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for PhysicsDone {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("PhysicsDone")
                    .field("quantum_number", &self.quantum_number())
                    .field("status", &self.status())
                    .field("reserved", &self.reserved())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for PhysicsDone {}
        impl<'a> ::flatbuffers::Follow<'a> for PhysicsDone {
            type Inner = &'a PhysicsDone;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a PhysicsDone>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a PhysicsDone {
            type Inner = &'a PhysicsDone;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<PhysicsDone>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for PhysicsDone {
            type Output = PhysicsDone;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const PhysicsDone as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for PhysicsDone {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> PhysicsDone {
            #[allow(clippy::too_many_arguments)]
            pub fn new(quantum_number: u64, status: u32, reserved: u32) -> Self {
                let mut s = Self([0; 16]);
                s.set_quantum_number(quantum_number);
                s.set_status(status);
                s.set_reserved(reserved);
                s
            }

            /// Must match the quantum_number in the corresponding PhysicsTrigger.
            pub fn quantum_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_quantum_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            /// 0 = OK, 1 = physics engine error (simulation will abort).
            pub fn status(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_status(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            /// Reserved — must be zero.
            pub fn reserved(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[12..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_reserved(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[12..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        pub enum ActuatorSampleOffset {}
        #[derive(Copy, Clone, PartialEq)]

        /// A single actuator command from one firmware node for one quantum.
        /// Carried inside PhysicsTrigger; not used on the Zenoh actuator bus directly.
        pub struct ActuatorSample<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for ActuatorSample<'a> {
            type Inner = ActuatorSample<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> ActuatorSample<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_ACTUATOR_ID: ::flatbuffers::VOffsetT = 6;
            pub const VT_VALUES: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                ActuatorSample { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args ActuatorSampleArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<ActuatorSample<'bldr>> {
                let mut builder = ActuatorSampleBuilder::new(_fbb);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                if let Some(x) = args.values {
                    builder.add_values(x);
                }
                builder.add_actuator_id(args.actuator_id);
                builder.finish()
            }

            /// Virtual time (ns) at which the firmware issued this command.
            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(ActuatorSample::VT_DELIVERY_VTIME_NS, Some(0)).unwrap()
                }
            }
            /// Actuator index as defined in the board topology.
            #[inline]
            pub fn actuator_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(ActuatorSample::VT_ACTUATOR_ID, Some(0)).unwrap() }
            }
            /// Actuator values (length = data_size declared in board YAML).
            #[inline]
            pub fn values(&self) -> Option<::flatbuffers::Vector<'a, f64>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f64>>>(
                        ActuatorSample::VT_VALUES,
                        None,
                    )
                }
            }
        }

        impl ::flatbuffers::Verifiable for ActuatorSample<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<u32>("actuator_id", Self::VT_ACTUATOR_ID, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f64>>>(
                        "values",
                        Self::VT_VALUES,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct ActuatorSampleArgs<'a> {
            pub delivery_vtime_ns: u64,
            pub actuator_id: u32,
            pub values: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f64>>>,
        }
        impl<'a> Default for ActuatorSampleArgs<'a> {
            #[inline]
            fn default() -> Self {
                ActuatorSampleArgs { delivery_vtime_ns: 0, actuator_id: 0, values: None }
            }
        }

        pub struct ActuatorSampleBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ActuatorSampleBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(
                    ActuatorSample::VT_DELIVERY_VTIME_NS,
                    delivery_vtime_ns,
                    0,
                );
            }
            #[inline]
            pub fn add_actuator_id(&mut self, actuator_id: u32) {
                self.fbb_.push_slot::<u32>(ActuatorSample::VT_ACTUATOR_ID, actuator_id, 0);
            }
            #[inline]
            pub fn add_values(
                &mut self,
                values: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, f64>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    ActuatorSample::VT_VALUES,
                    values,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> ActuatorSampleBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                ActuatorSampleBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<ActuatorSample<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for ActuatorSample<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("ActuatorSample");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("actuator_id", &self.actuator_id());
                ds.field("values", &self.values());
                ds.finish()
            }
        }
        pub enum PhysicsTriggerOffset {}
        #[derive(Copy, Clone, PartialEq)]

        /// Sent by the Time Authority to the Physics Gateway once per quantum.
        /// Contains the complete, causally-ordered set of actuator commands for
        /// the completed quantum.  The gateway MUST NOT step the physics engine
        /// until it receives this message.
        pub struct PhysicsTrigger<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for PhysicsTrigger<'a> {
            type Inner = PhysicsTrigger<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> PhysicsTrigger<'a> {
            pub const VT_QUANTUM_NUMBER: ::flatbuffers::VOffsetT = 4;
            pub const VT_QUANTUM_END_VTIME_NS: ::flatbuffers::VOffsetT = 6;
            pub const VT_ACTUATORS: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                PhysicsTrigger { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args PhysicsTriggerArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<PhysicsTrigger<'bldr>> {
                let mut builder = PhysicsTriggerBuilder::new(_fbb);
                builder.add_quantum_end_vtime_ns(args.quantum_end_vtime_ns);
                builder.add_quantum_number(args.quantum_number);
                if let Some(x) = args.actuators {
                    builder.add_actuators(x);
                }
                builder.finish()
            }

            /// Monotonically increasing quantum counter (matches ClockAdvanceReq.quantum_number).
            #[inline]
            pub fn quantum_number(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(PhysicsTrigger::VT_QUANTUM_NUMBER, Some(0)).unwrap() }
            }
            /// Virtual time (ns) at the END of the completed quantum
            /// (= absolute_vtime_ns + delta_ns from ClockAdvanceReq).
            #[inline]
            pub fn quantum_end_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(PhysicsTrigger::VT_QUANTUM_END_VTIME_NS, Some(0)).unwrap()
                }
            }
            /// All actuator commands collected during this quantum, ordered by
            /// (delivery_vtime_ns, actuator_id).
            #[inline]
            pub fn actuators(
                &self,
            ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ActuatorSample<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ActuatorSample>>,
                    >>(PhysicsTrigger::VT_ACTUATORS, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for PhysicsTrigger<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("quantum_number", Self::VT_QUANTUM_NUMBER, false)?
                    .visit_field::<u64>(
                        "quantum_end_vtime_ns",
                        Self::VT_QUANTUM_END_VTIME_NS,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<
                        ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ActuatorSample>>,
                    >>("actuators", Self::VT_ACTUATORS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct PhysicsTriggerArgs<'a> {
            pub quantum_number: u64,
            pub quantum_end_vtime_ns: u64,
            pub actuators: Option<
                ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ActuatorSample<'a>>>,
                >,
            >,
        }
        impl<'a> Default for PhysicsTriggerArgs<'a> {
            #[inline]
            fn default() -> Self {
                PhysicsTriggerArgs { quantum_number: 0, quantum_end_vtime_ns: 0, actuators: None }
            }
        }

        pub struct PhysicsTriggerBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PhysicsTriggerBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_quantum_number(&mut self, quantum_number: u64) {
                self.fbb_.push_slot::<u64>(PhysicsTrigger::VT_QUANTUM_NUMBER, quantum_number, 0);
            }
            #[inline]
            pub fn add_quantum_end_vtime_ns(&mut self, quantum_end_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(
                    PhysicsTrigger::VT_QUANTUM_END_VTIME_NS,
                    quantum_end_vtime_ns,
                    0,
                );
            }
            #[inline]
            pub fn add_actuators(
                &mut self,
                actuators: ::flatbuffers::WIPOffset<
                    ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<ActuatorSample<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    PhysicsTrigger::VT_ACTUATORS,
                    actuators,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> PhysicsTriggerBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                PhysicsTriggerBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<PhysicsTrigger<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for PhysicsTrigger<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("PhysicsTrigger");
                ds.field("quantum_number", &self.quantum_number());
                ds.field("quantum_end_vtime_ns", &self.quantum_end_vtime_ns());
                ds.field("actuators", &self.actuators());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `PhysicsTrigger`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_physics_trigger_unchecked`.
        pub fn root_as_physics_trigger(
            buf: &[u8],
        ) -> Result<PhysicsTrigger<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<PhysicsTrigger>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `PhysicsTrigger` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_physics_trigger_unchecked`.
        pub fn size_prefixed_root_as_physics_trigger(
            buf: &[u8],
        ) -> Result<PhysicsTrigger<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<PhysicsTrigger>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `PhysicsTrigger` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_physics_trigger_unchecked`.
        pub fn root_as_physics_trigger_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<PhysicsTrigger<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<PhysicsTrigger<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `PhysicsTrigger` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_physics_trigger_unchecked`.
        pub fn size_prefixed_root_as_physics_trigger_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<PhysicsTrigger<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<PhysicsTrigger<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a PhysicsTrigger and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `PhysicsTrigger`.
        pub unsafe fn root_as_physics_trigger_unchecked(buf: &[u8]) -> PhysicsTrigger<'_> {
            unsafe { ::flatbuffers::root_unchecked::<PhysicsTrigger>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed PhysicsTrigger and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `PhysicsTrigger`.
        pub unsafe fn size_prefixed_root_as_physics_trigger_unchecked(
            buf: &[u8],
        ) -> PhysicsTrigger<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<PhysicsTrigger>(buf) }
        }
        #[inline]
        pub fn finish_physics_trigger_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<PhysicsTrigger<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_physics_trigger_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<PhysicsTrigger<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod physics
} // pub mod virtmcu
