// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod rf_802154 {

        pub enum Rf802154HeaderOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Rf802154Header<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Rf802154Header<'a> {
            type Inner = Rf802154Header<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> Rf802154Header<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_SEQUENCE_NUMBER: ::flatbuffers::VOffsetT = 6;
            pub const VT_SIZE: ::flatbuffers::VOffsetT = 8;
            pub const VT_RSSI: ::flatbuffers::VOffsetT = 10;
            pub const VT_LQI: ::flatbuffers::VOffsetT = 12;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Rf802154Header { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args Rf802154HeaderArgs,
            ) -> ::flatbuffers::WIPOffset<Rf802154Header<'bldr>> {
                let mut builder = Rf802154HeaderBuilder::new(_fbb);
                builder.add_sequence_number(args.sequence_number);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                builder.add_size(args.size);
                builder.add_lqi(args.lqi);
                builder.add_rssi(args.rssi);
                builder.finish()
            }

            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(Rf802154Header::VT_DELIVERY_VTIME_NS, Some(0)).unwrap()
                }
            }
            #[inline]
            pub fn sequence_number(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(Rf802154Header::VT_SEQUENCE_NUMBER, Some(0)).unwrap()
                }
            }
            #[inline]
            pub fn size(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(Rf802154Header::VT_SIZE, Some(0)).unwrap() }
            }
            #[inline]
            pub fn rssi(&self) -> i8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i8>(Rf802154Header::VT_RSSI, Some(0)).unwrap() }
            }
            #[inline]
            pub fn lqi(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(Rf802154Header::VT_LQI, Some(255)).unwrap() }
            }
        }

        impl ::flatbuffers::Verifiable for Rf802154Header<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<u64>("sequence_number", Self::VT_SEQUENCE_NUMBER, false)?
                    .visit_field::<u32>("size", Self::VT_SIZE, false)?
                    .visit_field::<i8>("rssi", Self::VT_RSSI, false)?
                    .visit_field::<u8>("lqi", Self::VT_LQI, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct Rf802154HeaderArgs {
            pub delivery_vtime_ns: u64,
            pub sequence_number: u64,
            pub size: u32,
            pub rssi: i8,
            pub lqi: u8,
        }
        impl<'a> Default for Rf802154HeaderArgs {
            #[inline]
            fn default() -> Self {
                Rf802154HeaderArgs {
                    delivery_vtime_ns: 0,
                    sequence_number: 0,
                    size: 0,
                    rssi: 0,
                    lqi: 255,
                }
            }
        }

        pub struct Rf802154HeaderBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Rf802154HeaderBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(
                    Rf802154Header::VT_DELIVERY_VTIME_NS,
                    delivery_vtime_ns,
                    0,
                );
            }
            #[inline]
            pub fn add_sequence_number(&mut self, sequence_number: u64) {
                self.fbb_.push_slot::<u64>(Rf802154Header::VT_SEQUENCE_NUMBER, sequence_number, 0);
            }
            #[inline]
            pub fn add_size(&mut self, size: u32) {
                self.fbb_.push_slot::<u32>(Rf802154Header::VT_SIZE, size, 0);
            }
            #[inline]
            pub fn add_rssi(&mut self, rssi: i8) {
                self.fbb_.push_slot::<i8>(Rf802154Header::VT_RSSI, rssi, 0);
            }
            #[inline]
            pub fn add_lqi(&mut self, lqi: u8) {
                self.fbb_.push_slot::<u8>(Rf802154Header::VT_LQI, lqi, 255);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> Rf802154HeaderBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                Rf802154HeaderBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Rf802154Header<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Rf802154Header<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Rf802154Header");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("sequence_number", &self.sequence_number());
                ds.field("size", &self.size());
                ds.field("rssi", &self.rssi());
                ds.field("lqi", &self.lqi());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `Rf802154Header`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_rf_802154_header_unchecked`.
        pub fn root_as_rf_802154_header(
            buf: &[u8],
        ) -> Result<Rf802154Header<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<Rf802154Header>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `Rf802154Header` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_rf_802154_header_unchecked`.
        pub fn size_prefixed_root_as_rf_802154_header(
            buf: &[u8],
        ) -> Result<Rf802154Header<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<Rf802154Header>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `Rf802154Header` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_rf_802154_header_unchecked`.
        pub fn root_as_rf_802154_header_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Rf802154Header<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<Rf802154Header<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `Rf802154Header` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_rf_802154_header_unchecked`.
        pub fn size_prefixed_root_as_rf_802154_header_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Rf802154Header<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<Rf802154Header<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a Rf802154Header and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `Rf802154Header`.
        pub unsafe fn root_as_rf_802154_header_unchecked(buf: &[u8]) -> Rf802154Header<'_> {
            unsafe { ::flatbuffers::root_unchecked::<Rf802154Header>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed Rf802154Header and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `Rf802154Header`.
        pub unsafe fn size_prefixed_root_as_rf_802154_header_unchecked(
            buf: &[u8],
        ) -> Rf802154Header<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Rf802154Header>(buf) }
        }
        #[inline]
        pub fn finish_rf_802154_header_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<Rf802154Header<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_rf_802154_header_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<Rf802154Header<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod rf802154
} // pub mod virtmcu
