/* Generated by virtmcu-cli from hw/defs/reference.svd */
#pragma once

#include <stdint.h>
#include <stddef.h>

struct REFERENCE_PERIPHERAL {
    volatile uint32_t STATUS;
    volatile uint32_t TX;
    volatile uint32_t RX;
};

_Static_assert(offsetof(struct REFERENCE_PERIPHERAL, STATUS) == 0x00, "Offset mismatch");
_Static_assert(offsetof(struct REFERENCE_PERIPHERAL, TX) == 0x04, "Offset mismatch");
_Static_assert(offsetof(struct REFERENCE_PERIPHERAL, RX) == 0x08, "Offset mismatch");

#define REFERENCE_PERIPHERAL_BASE 0x09005000
#define REFERENCE_PERIPHERAL ((volatile struct REFERENCE_PERIPHERAL *) REFERENCE_PERIPHERAL_BASE)

