#!/usr/bin/env python3
"""
scripts/sync-protocols.py

Automated synchronization of binary protocols between Rust and Python.
Source of truth: hw/rust/common/virtmcu-api/src/lib.rs
Output: tools/python/virtmcu_api/protocols.py
"""

import argparse
import re
import sys
from pathlib import Path

# Mapping from Rust types to struct.pack format characters
TYPE_MAP = {
    "u64": "Q",
    "u32": "I",
    "u16": "H",
    "u8": "B",
    "bool": "B",  # In repr(C, packed), bool is usually 1 byte
}

STRUCT_HEADER = """# AUTO-GENERATED by scripts/sync-protocols.py - DO NOT EDIT
import struct
from dataclasses import dataclass
from typing import ClassVar

"""

def parse_rust_structs(content):
    """
    More robust parser for #[repr(C, packed)] structs in Rust.
    """
    structs = []

    # Match structs with #[repr(C, packed)]
    # This regex is more permissive about what's between #[repr...] and pub struct
    struct_pattern = re.compile(
        r"#\[repr\(C, packed\)\]\s+.*?pub struct (\w+) \{(.*?)\}",
        re.DOTALL
    )

    # Match fields, ignoring comments
    # Matches: pub name: type,
    field_pattern = re.compile(r"pub (\w+):\s+([^,]+),")

    for struct_match in struct_pattern.finditer(content):
        name = struct_match.group(1)
        fields_str = struct_match.group(2)

        # Clean up fields_str: remove comments
        fields_str = re.sub(r"///.*?\n", "", fields_str)
        fields_str = re.sub(r"//.*?\n", "", fields_str)

        fields = []
        for f_match in field_pattern.finditer(fields_str):
            f_name = f_match.group(1)
            f_type = f_match.group(2).strip()

            # Handle [u8; N] as padding
            padding_match = re.match(r"\[u8;\s*(\d+)\]", f_type)
            if padding_match:
                n = int(padding_match.group(1))
                fields.append((f_name, f"padding_{n}"))
            else:
                fields.append((f_name, f_type))

        if fields:
            structs.append((name, fields))

    return structs

def generate_python(structs):
    output = [STRUCT_HEADER]

    for name, fields in structs:
        fmt_parts = ["<"]
        for _, t in fields:
            if t.startswith("padding_"):
                n = int(t.split("_")[1])
                fmt_parts.append(f"{n}x")
            else:
                fmt_parts.append(TYPE_MAP.get(t, "X"))

        fmt = "".join(fmt_parts)
        if "X" in fmt:
            print(f"Warning: Unknown type in struct {name}, skipping.")
            continue

        output.append("@dataclass(frozen=True)")
        output.append(f"class {name}:")
        real_fields = [f for f in fields if not f[1].startswith("padding_")]
        for f_name, f_type in real_fields:
            py_type = "int" if f_type != "bool" else "bool"
            output.append(f"    {f_name}: {py_type}")

        output.append("")
        output.append(f"    FORMAT: ClassVar[str] = '{fmt}'")
        output.append("    SIZE: ClassVar[int] = struct.calcsize(FORMAT)")
        output.append("")
        output.append("    def pack(self) -> bytes:")
        field_names = ", ".join([f"self.{f[0]}" for f in real_fields])
        output.append(f"        return struct.pack(self.FORMAT, {field_names})")
        output.append("")
        output.append("    @classmethod")
        output.append(f"    def unpack(cls, data: bytes) -> '{name}':")
        output.append("        return cls(*struct.unpack(cls.FORMAT, data[:cls.SIZE]))")
        output.append("\n")

    return "\n".join(output)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Check if generated file is up to date")
    args = parser.parse_args()

    workspace = Path(__file__).parent.parent
    rust_src = workspace / "hw/rust/common/virtmcu-api/src/lib.rs"
    py_dst = workspace / "tools/python/virtmcu_api/protocols.py"

    if not rust_src.exists():
        print(f"Error: Could not find {rust_src}")
        sys.exit(1)

    content = rust_src.read_text()
    structs = parse_rust_structs(content)

    if not structs:
        print("Warning: No structs found in Rust source.")
        sys.exit(0)

    generated = generate_python(structs)

    if args.check:
        if not py_dst.exists():
            print(f"Error: {py_dst} does not exist.")
            sys.exit(1)
        current = py_dst.read_text()
        if current != generated:
            print(f"Error: {py_dst} is out of sync with Rust source. Run scripts/sync-protocols.py")
            sys.exit(1)
        print("✅ Protocols are in sync.")
    else:
        py_dst.parent.mkdir(parents=True, exist_ok=True)
        py_dst.write_text(generated)
        print(f"✅ Generated {py_dst}")

if __name__ == "__main__":
    main()
