// automatically generated by the FlatBuffers compiler, do not modify
// @generated
#![allow(deprecated)] // virtmcu-allow: allow reasoning="Flatbuffers generated struct"
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod core {

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        // struct VirtmcuHandshake, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct VirtmcuHandshake(pub [u8; 16]);
        impl Default for VirtmcuHandshake {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for VirtmcuHandshake {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("VirtmcuHandshake")
                    .field("magic", &self.magic())
                    .field("version", &self.version())
                    .field("svd_hash", &self.svd_hash())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for VirtmcuHandshake {}
        impl<'a> ::flatbuffers::Follow<'a> for VirtmcuHandshake {
            type Inner = &'a VirtmcuHandshake;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a VirtmcuHandshake>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a VirtmcuHandshake {
            type Inner = &'a VirtmcuHandshake;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<VirtmcuHandshake>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for VirtmcuHandshake {
            type Output = VirtmcuHandshake;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const VirtmcuHandshake as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for VirtmcuHandshake {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> VirtmcuHandshake {
            #[allow(clippy::too_many_arguments)]
            pub fn new(magic: u32, version: u32, svd_hash: u64) -> Self {
                let mut s = Self([0; 16]);
                s.set_magic(magic);
                s.set_version(version);
                s.set_svd_hash(svd_hash);
                s
            }

            pub fn magic(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_magic(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn version(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_version(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn svd_hash(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_svd_hash(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct MmioReq, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct MmioReq(pub [u8; 32]);
        impl Default for MmioReq {
            fn default() -> Self {
                Self([0; 32])
            }
        }
        impl ::core::fmt::Debug for MmioReq {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("MmioReq")
                    .field("type_", &self.type_())
                    .field("size", &self.size())
                    .field("reserved1", &self.reserved1())
                    .field("reserved2", &self.reserved2())
                    .field("vtime_ns", &self.vtime_ns())
                    .field("addr", &self.addr())
                    .field("data", &self.data())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for MmioReq {}
        impl<'a> ::flatbuffers::Follow<'a> for MmioReq {
            type Inner = &'a MmioReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a MmioReq>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a MmioReq {
            type Inner = &'a MmioReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<MmioReq>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for MmioReq {
            type Output = MmioReq;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const MmioReq as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for MmioReq {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> MmioReq {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                type_: u8,
                size: u8,
                reserved1: u16,
                reserved2: u32,
                vtime_ns: u64,
                addr: u64,
                data: u64,
            ) -> Self {
                let mut s = Self([0; 32]);
                s.set_type_(type_);
                s.set_size(size);
                s.set_reserved1(reserved1);
                s.set_reserved2(reserved2);
                s.set_vtime_ns(vtime_ns);
                s.set_addr(addr);
                s.set_data(data);
                s
            }

            pub fn type_(&self) -> u8 {
                let mut mem =
                    ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit(
                    );
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_type_(&mut self, x: u8) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn size(&self) -> u8 {
                let mut mem =
                    ::core::mem::MaybeUninit::<<u8 as ::flatbuffers::EndianScalar>::Scalar>::uninit(
                    );
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[1..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_size(&mut self, x: u8) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[1..].as_mut_ptr(),
                        ::core::mem::size_of::<<u8 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn reserved1(&self) -> u16 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u16 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[2..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_reserved1(&mut self, x: u16) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[2..].as_mut_ptr(),
                        ::core::mem::size_of::<<u16 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn reserved2(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_reserved2(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn addr(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_addr(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn data(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[24..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_data(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[24..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct SyscMsg, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct SyscMsg(pub [u8; 16]);
        impl Default for SyscMsg {
            fn default() -> Self {
                Self([0; 16])
            }
        }
        impl ::core::fmt::Debug for SyscMsg {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("SyscMsg")
                    .field("type_", &self.type_())
                    .field("irq_num", &self.irq_num())
                    .field("data", &self.data())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for SyscMsg {}
        impl<'a> ::flatbuffers::Follow<'a> for SyscMsg {
            type Inner = &'a SyscMsg;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a SyscMsg>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a SyscMsg {
            type Inner = &'a SyscMsg;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<SyscMsg>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for SyscMsg {
            type Output = SyscMsg;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const SyscMsg as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for SyscMsg {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> SyscMsg {
            #[allow(clippy::too_many_arguments)]
            pub fn new(type_: u32, irq_num: u32, data: u64) -> Self {
                let mut s = Self([0; 16]);
                s.set_type_(type_);
                s.set_irq_num(irq_num);
                s.set_data(data);
                s
            }

            pub fn type_(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_type_(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn irq_num(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[4..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_irq_num(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[4..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn data(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_data(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct ClockAdvanceReq, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ClockAdvanceReq(pub [u8; 24]);
        impl Default for ClockAdvanceReq {
            fn default() -> Self {
                Self([0; 24])
            }
        }
        impl ::core::fmt::Debug for ClockAdvanceReq {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ClockAdvanceReq")
                    .field("delta_ns", &self.delta_ns())
                    .field("absolute_vtime_ns", &self.absolute_vtime_ns())
                    .field("quantum_number", &self.quantum_number())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ClockAdvanceReq {}
        impl<'a> ::flatbuffers::Follow<'a> for ClockAdvanceReq {
            type Inner = &'a ClockAdvanceReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ClockAdvanceReq>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a ClockAdvanceReq {
            type Inner = &'a ClockAdvanceReq;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ClockAdvanceReq>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for ClockAdvanceReq {
            type Output = ClockAdvanceReq;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const ClockAdvanceReq as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ClockAdvanceReq {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ClockAdvanceReq {
            #[allow(clippy::too_many_arguments)]
            pub fn new(delta_ns: u64, absolute_vtime_ns: u64, quantum_number: u64) -> Self {
                let mut s = Self([0; 24]);
                s.set_delta_ns(delta_ns);
                s.set_absolute_vtime_ns(absolute_vtime_ns);
                s.set_quantum_number(quantum_number);
                s
            }

            pub fn delta_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_delta_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn absolute_vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_absolute_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            pub fn quantum_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_quantum_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        // struct ClockReadyResp, aligned to 8
        #[repr(transparent)]
        #[derive(Clone, Copy, PartialEq)]
        pub struct ClockReadyResp(pub [u8; 24]);
        impl Default for ClockReadyResp {
            fn default() -> Self {
                Self([0; 24])
            }
        }
        impl ::core::fmt::Debug for ClockReadyResp {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                f.debug_struct("ClockReadyResp")
                    .field("current_vtime_ns", &self.current_vtime_ns())
                    .field("n_frames", &self.n_frames())
                    .field("error_code", &self.error_code())
                    .field("quantum_number", &self.quantum_number())
                    .finish()
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for ClockReadyResp {}
        impl<'a> ::flatbuffers::Follow<'a> for ClockReadyResp {
            type Inner = &'a ClockReadyResp;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { <&'a ClockReadyResp>::follow(buf, loc) }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for &'a ClockReadyResp {
            type Inner = &'a ClockReadyResp;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                unsafe { ::flatbuffers::follow_cast_ref::<ClockReadyResp>(buf, loc) }
            }
        }
        impl<'b> ::flatbuffers::Push for ClockReadyResp {
            type Output = ClockReadyResp;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                let src = unsafe {
                    ::core::slice::from_raw_parts(
                        self as *const ClockReadyResp as *const u8,
                        <Self as ::flatbuffers::Push>::size(),
                    )
                };
                dst.copy_from_slice(src);
            }
            #[inline]
            fn alignment() -> ::flatbuffers::PushAlignment {
                ::flatbuffers::PushAlignment::new(8)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for ClockReadyResp {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.in_buffer::<Self>(pos)
            }
        }

        impl<'a> ClockReadyResp {
            #[allow(clippy::too_many_arguments)]
            pub fn new(
                current_vtime_ns: u64,
                n_frames: u32,
                error_code: u32,
                quantum_number: u64,
            ) -> Self {
                let mut s = Self([0; 24]);
                s.set_current_vtime_ns(current_vtime_ns);
                s.set_n_frames(n_frames);
                s.set_error_code(error_code);
                s.set_quantum_number(quantum_number);
                s
            }

            /// Current virtual time in nanoseconds.
            pub fn current_vtime_ns(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[0..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_current_vtime_ns(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[0..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            /// Number of outbound frames bundled in this response.
            pub fn n_frames(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[8..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_n_frames(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[8..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            /// Error code (0 = OK, 1 = STALL).
            pub fn error_code(&self) -> u32 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u32 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[12..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_error_code(&mut self, x: u32) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[12..].as_mut_ptr(),
                        ::core::mem::size_of::<<u32 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }

            /// Global quantum sequence number.
            pub fn quantum_number(&self) -> u64 {
                let mut mem = ::core::mem::MaybeUninit::<
                    <u64 as ::flatbuffers::EndianScalar>::Scalar,
                >::uninit();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                ::flatbuffers::EndianScalar::from_little_endian(unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        self.0[16..].as_ptr(),
                        mem.as_mut_ptr() as *mut u8,
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                    mem.assume_init()
                })
            }

            pub fn set_quantum_number(&mut self, x: u64) {
                let x_le = ::flatbuffers::EndianScalar::to_little_endian(x);
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid value in this slot
                unsafe {
                    ::core::ptr::copy_nonoverlapping(
                        &x_le as *const _ as *const u8,
                        self.0[16..].as_mut_ptr(),
                        ::core::mem::size_of::<<u64 as ::flatbuffers::EndianScalar>::Scalar>(),
                    );
                }
            }
        }

        pub enum UdsRegistrationOffset {}
        #[derive(Copy, Clone, PartialEq)]

        /// Sent by each node as the first framed message after connecting to the coordinator UDS socket.
        /// Topic: "sim/coord/register"
        /// The coordinator panics if federation_id doesn't match topology or proto_version is unknown.
        pub struct UdsRegistration<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for UdsRegistration<'a> {
            type Inner = UdsRegistration<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> UdsRegistration<'a> {
            pub const VT_NODE_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_FEDERATION_ID: ::flatbuffers::VOffsetT = 6;
            pub const VT_PROTO_VERSION: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                UdsRegistration { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args UdsRegistrationArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<UdsRegistration<'bldr>> {
                let mut builder = UdsRegistrationBuilder::new(_fbb);
                builder.add_proto_version(args.proto_version);
                if let Some(x) = args.federation_id {
                    builder.add_federation_id(x);
                }
                builder.add_node_id(args.node_id);
                builder.finish()
            }

            #[inline]
            pub fn node_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(UdsRegistration::VT_NODE_ID, Some(0)).unwrap() }
            }
            #[inline]
            pub fn federation_id(&self) -> &'a str {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(
                            UdsRegistration::VT_FEDERATION_ID,
                            None,
                        )
                        .unwrap()
                }
            }
            #[inline]
            pub fn proto_version(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(UdsRegistration::VT_PROTO_VERSION, Some(0)).unwrap() }
            }
        }

        impl ::flatbuffers::Verifiable for UdsRegistration<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("node_id", Self::VT_NODE_ID, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "federation_id",
                        Self::VT_FEDERATION_ID,
                        true,
                    )?
                    .visit_field::<u32>("proto_version", Self::VT_PROTO_VERSION, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct UdsRegistrationArgs<'a> {
            pub node_id: u32,
            pub federation_id: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub proto_version: u32,
        }
        impl<'a> Default for UdsRegistrationArgs<'a> {
            #[inline]
            fn default() -> Self {
                UdsRegistrationArgs {
                    node_id: 0,
                    federation_id: None, // required field
                    proto_version: 0,
                }
            }
        }

        pub struct UdsRegistrationBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UdsRegistrationBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_node_id(&mut self, node_id: u32) {
                self.fbb_.push_slot::<u32>(UdsRegistration::VT_NODE_ID, node_id, 0);
            }
            #[inline]
            pub fn add_federation_id(&mut self, federation_id: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    UdsRegistration::VT_FEDERATION_ID,
                    federation_id,
                );
            }
            #[inline]
            pub fn add_proto_version(&mut self, proto_version: u32) {
                self.fbb_.push_slot::<u32>(UdsRegistration::VT_PROTO_VERSION, proto_version, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> UdsRegistrationBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                UdsRegistrationBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<UdsRegistration<'a>> {
                let o = self.fbb_.end_table(self.start_);
                self.fbb_.required(o, UdsRegistration::VT_FEDERATION_ID, "federation_id");
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for UdsRegistration<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("UdsRegistration");
                ds.field("node_id", &self.node_id());
                ds.field("federation_id", &self.federation_id());
                ds.field("proto_version", &self.proto_version());
                ds.finish()
            }
        }
        pub enum UdsQuantumStartOffset {}
        #[derive(Copy, Clone, PartialEq)]

        /// Sent by the coordinator to each node to advance to the next quantum.
        /// Topic: "sim/coord/start/{node_id}"
        /// Nodes must not deliver messages with delivery_vtime_ns > vtime_limit_ns in their DONE signal.
        pub struct UdsQuantumStart<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for UdsQuantumStart<'a> {
            type Inner = UdsQuantumStart<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> UdsQuantumStart<'a> {
            pub const VT_QUANTUM: ::flatbuffers::VOffsetT = 4;
            pub const VT_VTIME_LIMIT_NS: ::flatbuffers::VOffsetT = 6;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                UdsQuantumStart { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args UdsQuantumStartArgs,
            ) -> ::flatbuffers::WIPOffset<UdsQuantumStart<'bldr>> {
                let mut builder = UdsQuantumStartBuilder::new(_fbb);
                builder.add_vtime_limit_ns(args.vtime_limit_ns);
                builder.add_quantum(args.quantum);
                builder.finish()
            }

            #[inline]
            pub fn quantum(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(UdsQuantumStart::VT_QUANTUM, Some(0)).unwrap() }
            }
            #[inline]
            pub fn vtime_limit_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(UdsQuantumStart::VT_VTIME_LIMIT_NS, Some(0)).unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for UdsQuantumStart<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("quantum", Self::VT_QUANTUM, false)?
                    .visit_field::<u64>("vtime_limit_ns", Self::VT_VTIME_LIMIT_NS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct UdsQuantumStartArgs {
            pub quantum: u64,
            pub vtime_limit_ns: u64,
        }
        impl<'a> Default for UdsQuantumStartArgs {
            #[inline]
            fn default() -> Self {
                UdsQuantumStartArgs { quantum: 0, vtime_limit_ns: 0 }
            }
        }

        pub struct UdsQuantumStartBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> UdsQuantumStartBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_quantum(&mut self, quantum: u64) {
                self.fbb_.push_slot::<u64>(UdsQuantumStart::VT_QUANTUM, quantum, 0);
            }
            #[inline]
            pub fn add_vtime_limit_ns(&mut self, vtime_limit_ns: u64) {
                self.fbb_.push_slot::<u64>(UdsQuantumStart::VT_VTIME_LIMIT_NS, vtime_limit_ns, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> UdsQuantumStartBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                UdsQuantumStartBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<UdsQuantumStart<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for UdsQuantumStart<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("UdsQuantumStart");
                ds.field("quantum", &self.quantum());
                ds.field("vtime_limit_ns", &self.vtime_limit_ns());
                ds.finish()
            }
        }
        pub enum LinkRegistrationOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct LinkRegistration<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for LinkRegistration<'a> {
            type Inner = LinkRegistration<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> LinkRegistration<'a> {
            pub const VT_LINK_NAME: ::flatbuffers::VOffsetT = 4;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                LinkRegistration { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args LinkRegistrationArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<LinkRegistration<'bldr>> {
                let mut builder = LinkRegistrationBuilder::new(_fbb);
                if let Some(x) = args.link_name {
                    builder.add_link_name(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn link_name(&self) -> &'a str {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(
                            LinkRegistration::VT_LINK_NAME,
                            None,
                        )
                        .unwrap()
                }
            }
        }

        impl ::flatbuffers::Verifiable for LinkRegistration<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "link_name",
                        Self::VT_LINK_NAME,
                        true,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct LinkRegistrationArgs<'a> {
            pub link_name: Option<::flatbuffers::WIPOffset<&'a str>>,
        }
        impl<'a> Default for LinkRegistrationArgs<'a> {
            #[inline]
            fn default() -> Self {
                LinkRegistrationArgs {
      link_name: None, // required field
    }
            }
        }

        pub struct LinkRegistrationBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LinkRegistrationBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_link_name(&mut self, link_name: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    LinkRegistration::VT_LINK_NAME,
                    link_name,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> LinkRegistrationBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                LinkRegistrationBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<LinkRegistration<'a>> {
                let o = self.fbb_.end_table(self.start_);
                self.fbb_.required(o, LinkRegistration::VT_LINK_NAME, "link_name");
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for LinkRegistration<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("LinkRegistration");
                ds.field("link_name", &self.link_name());
                ds.finish()
            }
        }
        pub enum LinkAckOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct LinkAck<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for LinkAck<'a> {
            type Inner = LinkAck<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> LinkAck<'a> {
            pub const VT_LINK_ID: ::flatbuffers::VOffsetT = 4;
            pub const VT_STATUS: ::flatbuffers::VOffsetT = 6;
            pub const VT_ERROR_MSG: ::flatbuffers::VOffsetT = 8;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                LinkAck { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args LinkAckArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<LinkAck<'bldr>> {
                let mut builder = LinkAckBuilder::new(_fbb);
                if let Some(x) = args.error_msg {
                    builder.add_error_msg(x);
                }
                builder.add_link_id(args.link_id);
                builder.add_status(args.status);
                builder.finish()
            }

            #[inline]
            pub fn link_id(&self) -> u32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u32>(LinkAck::VT_LINK_ID, Some(0)).unwrap() }
            }
            #[inline]
            pub fn status(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(LinkAck::VT_STATUS, Some(0)).unwrap() }
            }
            #[inline]
            pub fn error_msg(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<&str>>(LinkAck::VT_ERROR_MSG, None)
                }
            }
        }

        impl ::flatbuffers::Verifiable for LinkAck<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u32>("link_id", Self::VT_LINK_ID, false)?
                    .visit_field::<u8>("status", Self::VT_STATUS, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "error_msg",
                        Self::VT_ERROR_MSG,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct LinkAckArgs<'a> {
            pub link_id: u32,
            pub status: u8,
            pub error_msg: Option<::flatbuffers::WIPOffset<&'a str>>,
        }
        impl<'a> Default for LinkAckArgs<'a> {
            #[inline]
            fn default() -> Self {
                LinkAckArgs { link_id: 0, status: 0, error_msg: None }
            }
        }

        pub struct LinkAckBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LinkAckBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_link_id(&mut self, link_id: u32) {
                self.fbb_.push_slot::<u32>(LinkAck::VT_LINK_ID, link_id, 0);
            }
            #[inline]
            pub fn add_status(&mut self, status: u8) {
                self.fbb_.push_slot::<u8>(LinkAck::VT_STATUS, status, 0);
            }
            #[inline]
            pub fn add_error_msg(&mut self, error_msg: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    LinkAck::VT_ERROR_MSG,
                    error_msg,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> LinkAckBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                LinkAckBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<LinkAck<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for LinkAck<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("LinkAck");
                ds.field("link_id", &self.link_id());
                ds.field("status", &self.status());
                ds.field("error_msg", &self.error_msg());
                ds.finish()
            }
        }
    } // pub mod core
} // pub mod virtmcu
