// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod insn_trace {

        pub enum InsnTraceOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct InsnTrace<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for InsnTrace<'a> {
            type Inner = InsnTrace<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> InsnTrace<'a> {
            pub const VT_TIMESTAMP_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_PC: ::flatbuffers::VOffsetT = 6;
            pub const VT_DISASSEMBLY: ::flatbuffers::VOffsetT = 8;
            pub const VT_QUANTUM_NUMBER: ::flatbuffers::VOffsetT = 10;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                InsnTrace { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args InsnTraceArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<InsnTrace<'bldr>> {
                let mut builder = InsnTraceBuilder::new(_fbb);
                builder.add_quantum_number(args.quantum_number);
                builder.add_pc(args.pc);
                builder.add_timestamp_ns(args.timestamp_ns);
                if let Some(x) = args.disassembly {
                    builder.add_disassembly(x);
                }
                builder.finish()
            }

            /// Virtual timestamp in nanoseconds since simulation start.
            #[inline]
            pub fn timestamp_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(InsnTrace::VT_TIMESTAMP_NS, Some(0)).unwrap() }
            }
            /// Program counter of the executed instruction.
            #[inline]
            pub fn pc(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(InsnTrace::VT_PC, Some(0)).unwrap() }
            }
            /// Disassembly string (e.g. "mov r0, #1"). May be empty when disassembly is disabled.
            #[inline]
            pub fn disassembly(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                        InsnTrace::VT_DISASSEMBLY,
                        None,
                    )
                }
            }
            /// Quantum number in which this instruction executed.
            #[inline]
            pub fn quantum_number(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(InsnTrace::VT_QUANTUM_NUMBER, Some(0)).unwrap() }
            }
        }

        impl ::flatbuffers::Verifiable for InsnTrace<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("timestamp_ns", Self::VT_TIMESTAMP_NS, false)?
                    .visit_field::<u64>("pc", Self::VT_PC, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                        "disassembly",
                        Self::VT_DISASSEMBLY,
                        false,
                    )?
                    .visit_field::<u64>("quantum_number", Self::VT_QUANTUM_NUMBER, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct InsnTraceArgs<'a> {
            pub timestamp_ns: u64,
            pub pc: u64,
            pub disassembly: Option<::flatbuffers::WIPOffset<&'a str>>,
            pub quantum_number: u64,
        }
        impl<'a> Default for InsnTraceArgs<'a> {
            #[inline]
            fn default() -> Self {
                InsnTraceArgs { timestamp_ns: 0, pc: 0, disassembly: None, quantum_number: 0 }
            }
        }

        pub struct InsnTraceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> InsnTraceBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_timestamp_ns(&mut self, timestamp_ns: u64) {
                self.fbb_.push_slot::<u64>(InsnTrace::VT_TIMESTAMP_NS, timestamp_ns, 0);
            }
            #[inline]
            pub fn add_pc(&mut self, pc: u64) {
                self.fbb_.push_slot::<u64>(InsnTrace::VT_PC, pc, 0);
            }
            #[inline]
            pub fn add_disassembly(&mut self, disassembly: ::flatbuffers::WIPOffset<&'b str>) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    InsnTrace::VT_DISASSEMBLY,
                    disassembly,
                );
            }
            #[inline]
            pub fn add_quantum_number(&mut self, quantum_number: u64) {
                self.fbb_.push_slot::<u64>(InsnTrace::VT_QUANTUM_NUMBER, quantum_number, 0);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> InsnTraceBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                InsnTraceBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<InsnTrace<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for InsnTrace<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("InsnTrace");
                ds.field("timestamp_ns", &self.timestamp_ns());
                ds.field("pc", &self.pc());
                ds.field("disassembly", &self.disassembly());
                ds.field("quantum_number", &self.quantum_number());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `InsnTrace`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_insn_trace_unchecked`.
        pub fn root_as_insn_trace(
            buf: &[u8],
        ) -> Result<InsnTrace<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<InsnTrace>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `InsnTrace` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_insn_trace_unchecked`.
        pub fn size_prefixed_root_as_insn_trace(
            buf: &[u8],
        ) -> Result<InsnTrace<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<InsnTrace>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `InsnTrace` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_insn_trace_unchecked`.
        pub fn root_as_insn_trace_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<InsnTrace<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<InsnTrace<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `InsnTrace` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_insn_trace_unchecked`.
        pub fn size_prefixed_root_as_insn_trace_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<InsnTrace<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<InsnTrace<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a InsnTrace and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `InsnTrace`.
        pub unsafe fn root_as_insn_trace_unchecked(buf: &[u8]) -> InsnTrace<'_> {
            unsafe { ::flatbuffers::root_unchecked::<InsnTrace>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed InsnTrace and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `InsnTrace`.
        pub unsafe fn size_prefixed_root_as_insn_trace_unchecked(buf: &[u8]) -> InsnTrace<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<InsnTrace>(buf) }
        }
        #[inline]
        pub fn finish_insn_trace_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<InsnTrace<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_insn_trace_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<InsnTrace<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod InsnTrace
} // pub mod Virtmcu
