// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod virtmcu {

    #[allow(unused_imports, dead_code)]
    pub mod rf_802154 {

        pub enum Rf802154FrameOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Rf802154Frame<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for Rf802154Frame<'a> {
            type Inner = Rf802154Frame<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
            }
        }

        impl<'a> Rf802154Frame<'a> {
            pub const VT_DELIVERY_VTIME_NS: ::flatbuffers::VOffsetT = 4;
            pub const VT_SEQUENCE_NUMBER: ::flatbuffers::VOffsetT = 6;
            pub const VT_RSSI: ::flatbuffers::VOffsetT = 8;
            pub const VT_LQI: ::flatbuffers::VOffsetT = 10;
            pub const VT_FCF: ::flatbuffers::VOffsetT = 12;
            pub const VT_MHR_SEQ_NUM: ::flatbuffers::VOffsetT = 14;
            pub const VT_DEST_PAN: ::flatbuffers::VOffsetT = 16;
            pub const VT_DEST_ADDR: ::flatbuffers::VOffsetT = 18;
            pub const VT_SRC_PAN: ::flatbuffers::VOffsetT = 20;
            pub const VT_SRC_ADDR: ::flatbuffers::VOffsetT = 22;
            pub const VT_DATA: ::flatbuffers::VOffsetT = 24;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                Rf802154Frame { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args Rf802154FrameArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<Rf802154Frame<'bldr>> {
                let mut builder = Rf802154FrameBuilder::new(_fbb);
                builder.add_src_addr(args.src_addr);
                builder.add_dest_addr(args.dest_addr);
                builder.add_sequence_number(args.sequence_number);
                builder.add_delivery_vtime_ns(args.delivery_vtime_ns);
                if let Some(x) = args.data {
                    builder.add_data(x);
                }
                builder.add_src_pan(args.src_pan);
                builder.add_dest_pan(args.dest_pan);
                builder.add_fcf(args.fcf);
                builder.add_mhr_seq_num(args.mhr_seq_num);
                builder.add_lqi(args.lqi);
                builder.add_rssi(args.rssi);
                builder.finish()
            }

            #[inline]
            pub fn delivery_vtime_ns(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<u64>(Rf802154Frame::VT_DELIVERY_VTIME_NS, Some(0)).unwrap()
                }
            }
            #[inline]
            pub fn sequence_number(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u64>(Rf802154Frame::VT_SEQUENCE_NUMBER, Some(0)).unwrap() }
            }
            #[inline]
            pub fn rssi(&self) -> i8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<i8>(Rf802154Frame::VT_RSSI, Some(0)).unwrap() }
            }
            #[inline]
            pub fn lqi(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(Rf802154Frame::VT_LQI, Some(255)).unwrap() }
            }
            #[inline]
            pub fn fcf(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u16>(Rf802154Frame::VT_FCF, Some(0)).unwrap() }
            }
            #[inline]
            pub fn mhr_seq_num(&self) -> u8 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u8>(Rf802154Frame::VT_MHR_SEQ_NUM, Some(0)).unwrap() }
            }
            #[inline]
            pub fn dest_pan(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u16>(Rf802154Frame::VT_DEST_PAN, Some(65535)).unwrap() }
            }
            #[inline]
            pub fn dest_addr(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(Rf802154Frame::VT_DEST_ADDR, Some(18446744073709551615))
                        .unwrap()
                }
            }
            #[inline]
            pub fn src_pan(&self) -> u16 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe { self._tab.get::<u16>(Rf802154Frame::VT_SRC_PAN, Some(65535)).unwrap() }
            }
            #[inline]
            pub fn src_addr(&self) -> u64 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<u64>(Rf802154Frame::VT_SRC_ADDR, Some(18446744073709551615))
                        .unwrap()
                }
            }
            #[inline]
            pub fn data(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        Rf802154Frame::VT_DATA,
                        None,
                    )
                }
            }
        }

        impl ::flatbuffers::Verifiable for Rf802154Frame<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<u64>("delivery_vtime_ns", Self::VT_DELIVERY_VTIME_NS, false)?
                    .visit_field::<u64>("sequence_number", Self::VT_SEQUENCE_NUMBER, false)?
                    .visit_field::<i8>("rssi", Self::VT_RSSI, false)?
                    .visit_field::<u8>("lqi", Self::VT_LQI, false)?
                    .visit_field::<u16>("fcf", Self::VT_FCF, false)?
                    .visit_field::<u8>("mhr_seq_num", Self::VT_MHR_SEQ_NUM, false)?
                    .visit_field::<u16>("dest_pan", Self::VT_DEST_PAN, false)?
                    .visit_field::<u64>("dest_addr", Self::VT_DEST_ADDR, false)?
                    .visit_field::<u16>("src_pan", Self::VT_SRC_PAN, false)?
                    .visit_field::<u64>("src_addr", Self::VT_SRC_ADDR, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "data",
                        Self::VT_DATA,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct Rf802154FrameArgs<'a> {
            pub delivery_vtime_ns: u64,
            pub sequence_number: u64,
            pub rssi: i8,
            pub lqi: u8,
            pub fcf: u16,
            pub mhr_seq_num: u8,
            pub dest_pan: u16,
            pub dest_addr: u64,
            pub src_pan: u16,
            pub src_addr: u64,
            pub data: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        }
        impl<'a> Default for Rf802154FrameArgs<'a> {
            #[inline]
            fn default() -> Self {
                Rf802154FrameArgs {
                    delivery_vtime_ns: 0,
                    sequence_number: 0,
                    rssi: 0,
                    lqi: 255,
                    fcf: 0,
                    mhr_seq_num: 0,
                    dest_pan: 65535,
                    dest_addr: 18446744073709551615,
                    src_pan: 65535,
                    src_addr: 18446744073709551615,
                    data: None,
                }
            }
        }

        pub struct Rf802154FrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> Rf802154FrameBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_delivery_vtime_ns(&mut self, delivery_vtime_ns: u64) {
                self.fbb_.push_slot::<u64>(
                    Rf802154Frame::VT_DELIVERY_VTIME_NS,
                    delivery_vtime_ns,
                    0,
                );
            }
            #[inline]
            pub fn add_sequence_number(&mut self, sequence_number: u64) {
                self.fbb_.push_slot::<u64>(Rf802154Frame::VT_SEQUENCE_NUMBER, sequence_number, 0);
            }
            #[inline]
            pub fn add_rssi(&mut self, rssi: i8) {
                self.fbb_.push_slot::<i8>(Rf802154Frame::VT_RSSI, rssi, 0);
            }
            #[inline]
            pub fn add_lqi(&mut self, lqi: u8) {
                self.fbb_.push_slot::<u8>(Rf802154Frame::VT_LQI, lqi, 255);
            }
            #[inline]
            pub fn add_fcf(&mut self, fcf: u16) {
                self.fbb_.push_slot::<u16>(Rf802154Frame::VT_FCF, fcf, 0);
            }
            #[inline]
            pub fn add_mhr_seq_num(&mut self, mhr_seq_num: u8) {
                self.fbb_.push_slot::<u8>(Rf802154Frame::VT_MHR_SEQ_NUM, mhr_seq_num, 0);
            }
            #[inline]
            pub fn add_dest_pan(&mut self, dest_pan: u16) {
                self.fbb_.push_slot::<u16>(Rf802154Frame::VT_DEST_PAN, dest_pan, 65535);
            }
            #[inline]
            pub fn add_dest_addr(&mut self, dest_addr: u64) {
                self.fbb_.push_slot::<u64>(
                    Rf802154Frame::VT_DEST_ADDR,
                    dest_addr,
                    18446744073709551615,
                );
            }
            #[inline]
            pub fn add_src_pan(&mut self, src_pan: u16) {
                self.fbb_.push_slot::<u16>(Rf802154Frame::VT_SRC_PAN, src_pan, 65535);
            }
            #[inline]
            pub fn add_src_addr(&mut self, src_addr: u64) {
                self.fbb_.push_slot::<u64>(
                    Rf802154Frame::VT_SRC_ADDR,
                    src_addr,
                    18446744073709551615,
                );
            }
            #[inline]
            pub fn add_data(
                &mut self,
                data: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(Rf802154Frame::VT_DATA, data);
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> Rf802154FrameBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                Rf802154FrameBuilder { fbb_: _fbb, start_: start }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<Rf802154Frame<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for Rf802154Frame<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("Rf802154Frame");
                ds.field("delivery_vtime_ns", &self.delivery_vtime_ns());
                ds.field("sequence_number", &self.sequence_number());
                ds.field("rssi", &self.rssi());
                ds.field("lqi", &self.lqi());
                ds.field("fcf", &self.fcf());
                ds.field("mhr_seq_num", &self.mhr_seq_num());
                ds.field("dest_pan", &self.dest_pan());
                ds.field("dest_addr", &self.dest_addr());
                ds.field("src_pan", &self.src_pan());
                ds.field("src_addr", &self.src_addr());
                ds.field("data", &self.data());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `Rf802154Frame`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_rf_802154_frame_unchecked`.
        pub fn root_as_rf_802154_frame(
            buf: &[u8],
        ) -> Result<Rf802154Frame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<Rf802154Frame>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `Rf802154Frame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_rf_802154_frame_unchecked`.
        pub fn size_prefixed_root_as_rf_802154_frame(
            buf: &[u8],
        ) -> Result<Rf802154Frame<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<Rf802154Frame>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `Rf802154Frame` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_rf_802154_frame_unchecked`.
        pub fn root_as_rf_802154_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Rf802154Frame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<Rf802154Frame<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `Rf802154Frame` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_rf_802154_frame_unchecked`.
        pub fn size_prefixed_root_as_rf_802154_frame_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Rf802154Frame<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<Rf802154Frame<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a Rf802154Frame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `Rf802154Frame`.
        pub unsafe fn root_as_rf_802154_frame_unchecked(buf: &[u8]) -> Rf802154Frame<'_> {
            unsafe { ::flatbuffers::root_unchecked::<Rf802154Frame>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed Rf802154Frame and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `Rf802154Frame`.
        pub unsafe fn size_prefixed_root_as_rf_802154_frame_unchecked(
            buf: &[u8],
        ) -> Rf802154Frame<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Rf802154Frame>(buf) }
        }
        #[inline]
        pub fn finish_rf_802154_frame_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<Rf802154Frame<'a>>,
        ) {
            fbb.finish(root, None);
        }

        #[inline]
        pub fn finish_size_prefixed_rf_802154_frame_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<Rf802154Frame<'a>>,
        ) {
            fbb.finish_size_prefixed(root, None);
        }
    } // pub mod rf802154
} // pub mod virtmcu
